spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${SPRING_DEV_DATASOURCE_URL}
    username: ${SPRING_DEV_DATASOURCE_USERNAME}
    password: ${SPRING_DEV_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        show_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_PROD_DATASOURCE_URL}
    username: ${SPRING_PROD_DATASOURCE_USERNAME}
    password: ${SPRING_PROD_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        show_sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: ${SPRING_TEST_DATASOURCE_URL}
    username: ${SPRING_TEST_DATASOURCE_USERNAME}
    password: ${SPRING_TEST_DATASOURCE_PASSWORD}
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        show_sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${SPRING_TEST_NAVER_CLIENTID}
            client-secret: ${SPRING_TEST_NAVER_CLIENTSECRET}
            scope: ${SPRING_TEST_NAVER_SCOPE}
            client-name: ${SPRING_TEST_NAVER_CLIENTNAME}
            authorization-grant-type: ${SPRING_TEST_NAVER_GRANTTYPE}
            redirect-uri: ${SPRING_TEST_NAVER_REDIRECT}

        provider:
          naver:
            authorization-uri: ${SPRING_TEST_NAVER_AUTHORIZATION-URI}
            token-uri: ${SPRING_TEST_NAVER_TOKEN-URI}
            user-info-uri: ${SPRING_TEST_NAVER_USER-INFO-URI}
            user-name-attribute: ${SPRING_TEST_NAVER_USER-NAME-ATTRIBUTE}

auth:
  jwt:
    issuer: ${TEST_JWT_ISSUER}
    secret: ${TEST_JWT_SECRET}
    accessTokenExpirationHour: ${TEST_JWT_ACCESSTOKENEXP}




