name: CD to EC2 Docker

on:
  push:
    branches: [ "main" ]

permissions:
  pull-requests: write
  checks: write
  contents: read

jobs:
  build:
    name: Install Ubuntu:latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          jq -r 'to_entries | map(select(.key != "PRIVATE_KEY")) | map("\(.key)=\(.value|tostring)") | .[]' <<< "$SECRETS_CONTEXT" > ./src/main/resources/.env
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: gradlew test
        run: ./gradlew test

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Build with Gradle
        run: ./gradlew build

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PWD }}
          version=$(grep -oP "(?<=version = \").*(?=\")" build.gradle.kts)
          docker build -t moveuk/zziririt:$version .
          docker image tag moveuk/zziririt:$version moveuk/zziririt:latest
          docker image ls -a
          docker push moveuk/zziririt:latest
          docker push moveuk/zziririt:$version

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            docker ps
            docker stop server
            docker rm server
            docker pull moveuk/zziririt
            docker run -d --rm --name server -v ~/app/logs:/home/logs -p 8080:8080 moveuk/zziririt